/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taf;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author maryo
 */
public class AffHis extends javax.swing.JInternalFrame {

    /**
     * Creates new form AffHis
     */
    public AffHis() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    DefaultTableModel tblModel;
    DefaultTableModel tblModel1;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ref = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabc = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Affichage de l’historique des consultations");
        setPreferredSize(new java.awt.Dimension(1450, 950));
        getContentPane().setLayout(null);

        tab.setBackground(new java.awt.Color(0, 0, 0));
        tab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tab.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        tab.setForeground(new java.awt.Color(255, 255, 255));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Référence", "Nom", "Prénom", "Sexe", "Date de naissance", "Numéro de téléphone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab.setRowHeight(30);
        tab.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 200, 1200, 60);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Référence:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 180, 140, 44);

        ref.setBackground(new java.awt.Color(0, 0, 0));
        ref.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        ref.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ref);
        ref.setBounds(10, 220, 190, 39);

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jButton1.setText("Afficher Historique");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 110, 350, 41);

        tabc.setBackground(new java.awt.Color(0, 0, 0));
        tabc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        tabc.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        tabc.setForeground(new java.awt.Color(255, 255, 255));
        tabc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date Consultation", "Diagnostic", "Nom Médicament", "Posologie", "Analyse", "Acte Radio", "Nom Spécialiste", "Spécialité"
            }
        ));
        tabc.setRowHeight(30);
        tabc.setSelectionBackground(new java.awt.Color(0, 102, 102));
        jScrollPane2.setViewportView(tabc);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 280, 1410, 580);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("Historique des consultations d'un patient");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 20, 983, 86);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jButton2.setText("Quitter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(940, 110, 170, 41);

        jButton3.setBackground(new java.awt.Color(255, 102, 0));
        jButton3.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jButton3.setText("Annuler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(230, 110, 170, 41);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taf/bg.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1440, 950);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  //dans le cas où l'utilisateur veut quitter le programme
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean test=false;
        boolean test1=false;
        String r=ref.getText();
        
        tblModel=(DefaultTableModel)tab.getModel();
        tblModel.setRowCount(0);
        tblModel1=(DefaultTableModel)tabc.getModel();
        tblModel1.setRowCount(0);
        
        
         /*verification référence est en digits seulement*/
        boolean t=true;
        for(int i=0;i<r.length();i++)
        {if(!Character.isDigit(r.charAt(i))){t=false; break;}} 
        //si la référence est invalide ou vide
        if(r.equals("")) JOptionPane.showMessageDialog(null,"Ecrire une référence SVP");
        else if(!t) JOptionPane.showMessageDialog(null,"Référence invalide");
        //sinon
        else{//création de la connexion avec la base de données
            try{Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");
                Statement st=con.createStatement();
                //requête d'affichage
                String sql="Select * from dossier";
                ResultSet rs=st.executeQuery(sql);
                //tant qu'il y a encore une ligne d'après dans la base on fait ça:
                while(rs.next())
                {//retrait des données de la base
                    String reff=String.valueOf(rs.getInt("Ref"));
                    String nom=String.valueOf(rs.getString("Nom"));
                    String pre=String.valueOf(rs.getString("Prenom"));
                    String s=String.valueOf(rs.getString("Sexe"));
                    String date;
                    String j=String.valueOf(rs.getString("Jour naissance"));
                    String m=String.valueOf(rs.getString("Mois naissance"));
                    String a=String.valueOf(rs.getString("Année naissance"));
                    date=j+" "+m+" "+a;//la dtae dans la base est divisée dans trois champs on les rassemble dans date
                    String tel=String.valueOf(rs.getString("tel"));
                    //si la référence est trouvée on met les valeurs obtenues dans le tableau pour afficher les cordonnées
                    //test aura true et le compteur du tableau aura la valeur 0 pour vider et attendre un nouvel patient à afficher
                    if(r.equals(reff)){String tbData[]={reff,nom,pre,s,date,tel};
                        tblModel=(DefaultTableModel)tab.getModel();
                        tblModel.setRowCount(0); tblModel.addRow(tbData); test=true;}}
                //si test ==false donc référence non trouvée
                if(test==false){DefaultTableModel tblModel=(DefaultTableModel)tab.getModel();
                    tblModel.setRowCount(0);JOptionPane.showMessageDialog(null,"Référence Introuvable");
                    //remttre le champ référence au vide
                    ref.setText("");}
                //fin connection
                con.close();
            } catch (Exception ex) {JOptionPane.showMessageDialog(null,ex);}

            /*affichage consultation et ses détails*/
            try{Class.forName("com.mysql.jdbc.Driver");//connection
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");
                Statement st=con.createStatement();
                String sql="Select * from consultation order by Datecons,Ref";//requête
                ResultSet rs=st.executeQuery(sql);

                while(rs.next())
                {String reff=String.valueOf(rs.getInt("Ref"));
                    String dc=String.valueOf(rs.getString("Datecons"));
                    String diag=String.valueOf(rs.getString("Diagnostic"));
                    String nm=String.valueOf(rs.getString("nomMed"));
                    String poso=String.valueOf(rs.getString("posologie"));
                    String an=String.valueOf(rs.getString("analyse"));
                    if(an.equals("")) an="  -";//s'il n'y a pas d'analyses alors un tiret s'affiche 
                    String ar=String.valueOf(rs.getString("radio"));
                    if(ar.equals("")) ar="  -";//s'il n'y a pas d'acte radio alors un tiret s'affiche 
                    String ns=String.valueOf(rs.getString("nom"));
                    String s=String.valueOf(rs.getString("spécialité"));
                    //affichage dans le tableau
                    if(r.equals(reff)){String tbData[]={dc,diag,nm,poso,an,ar,ns,s};
                        tblModel1=(DefaultTableModel)tabc.getModel();
                        tblModel1.addRow(tbData); test1=true;}}
                //sinon patient n'a pas de consultations
                if(test1==false){DefaultTableModel tblModel=(DefaultTableModel)tabc.getModel();
                    tblModel.setRowCount(0);JOptionPane.showMessageDialog(null,"Patient n'a pas de consultations");}
                //fin connection
                con.close();}
            catch (Exception e) {JOptionPane.showMessageDialog(null,e);}

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       //un bouton annuler pour initialiser la référence au vide et les deux tableaux de l'affichage
ref.setText("");
tblModel.setRowCount(0);
tblModel1.setRowCount(0);
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField ref;
    private javax.swing.JTable tab;
    private javax.swing.JTable tabc;
    // End of variables declaration//GEN-END:variables
}
