/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taf;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maryo
 */
public class AffPer extends javax.swing.JInternalFrame {

    /**
     * Creates new form AffPer
     */
    public AffPer() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    DefaultTableModel tblModel;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        ref = new javax.swing.JTextField();
        Valider = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Affichage des informations personnelles");
        setVisible(false);
        getContentPane().setLayout(null);

        tab.setBackground(new java.awt.Color(0, 0, 0));
        tab.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        tab.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        tab.setForeground(new java.awt.Color(255, 255, 255));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Référence", "Nom", "Prénom", "Sexe", "Date De Naissance", "Numéro de Téléphone"
            }
        ));
        tab.setRowHeight(30);
        tab.setSelectionBackground(new java.awt.Color(0, 51, 102));
        jScrollPane1.setViewportView(tab);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 320, 1410, 60);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Référence:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 250, 121, 44);

        ref.setBackground(new java.awt.Color(0, 0, 0));
        ref.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        ref.setForeground(new java.awt.Color(255, 255, 255));
        ref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refActionPerformed(evt);
            }
        });
        getContentPane().add(ref);
        ref.setBounds(540, 250, 265, 39);

        Valider.setBackground(new java.awt.Color(0, 244, 51));
        Valider.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        Valider.setText("Afficher Informations");
        Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValiderActionPerformed(evt);
            }
        });
        getContentPane().add(Valider);
        Valider.setBounds(500, 110, 350, 41);

        jLabel2.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Afficher les informations personnelles d'un patient");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 20, 1111, 45);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jButton2.setText("Quitter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(940, 110, 170, 41);

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 110, 170, 41);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taf/bg.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1440, 950);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValiderActionPerformed
        // TODO add your handling code here:
        boolean test=false;
        String r=ref.getText();
        
         /*verification référence est en digits seulement*/
        boolean t=true;
        for(int i=0;i<r.length();i++)
        {if(!Character.isDigit(r.charAt(i))){t=false; break;}} 
        
       
        if(r.equals("")) JOptionPane.showMessageDialog(null,"Ecrire une référence SVP");
        
        if(!r.equals("")){

         try{Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");
        Statement st=con.createStatement();
        String sql="Select * from dossier";
        ResultSet rs=st.executeQuery(sql);
        
       while(rs.next())
        {String reff=String.valueOf(rs.getInt("Ref"));
        String nom=String.valueOf(rs.getString("Nom"));
        String pre=String.valueOf(rs.getString("Prenom"));
        String s=String.valueOf(rs.getString("Sexe"));
        String j=String.valueOf(rs.getString("Jour naissance"));
        String m=String.valueOf(rs.getString("Mois naissance"));
        String a=String.valueOf(rs.getString("Année naissance"));
        String ch=j+" "+m+" "+a;
        String tel=String.valueOf(rs.getString("tel"));
            
        if(r.equals(reff)){String tbData[]={reff,nom,pre,s,ch,tel};
        tblModel=(DefaultTableModel)tab.getModel();
        tblModel.setRowCount(0); tblModel.addRow(tbData); test=true;}}
       if(test==false){DefaultTableModel tblModel=(DefaultTableModel)tab.getModel();
         tblModel.setRowCount(0); ref.setText("");
         JOptionPane.showMessageDialog(null,"Référence Introuvable");}
        con.close();} 
        catch (Exception ex) {JOptionPane.showMessageDialog(null,ex);}}
    }//GEN-LAST:event_ValiderActionPerformed

    private void refActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  //dans le cas où l'utilisateur veut quitter le programme
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //un bouton annuler pour initialiser la référence au vide et le tableau d'affichage
        ref.setText("");
        tblModel.setRowCount(0);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Valider;
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ref;
    private javax.swing.JTable tab;
    // End of variables declaration//GEN-END:variables
}
