package taf;
import java.sql.*;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author maryo
 */
public class CréerDossier extends javax.swing.JInternalFrame {

    /**
     * Creates new form CréerDossier
     */
    public CréerDossier() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexe = new javax.swing.ButtonGroup();
        nom = new javax.swing.JTextField();
        pre = new javax.swing.JTextField();
        tel = new javax.swing.JTextField();
        f = new javax.swing.JRadioButton();
        m = new javax.swing.JRadioButton();
        dd = new javax.swing.JComboBox<>();
        mm = new javax.swing.JComboBox<>();
        yy = new javax.swing.JComboBox<>();
        valider = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Création d’un nouveau dossier médical");
        setNormalBounds(new java.awt.Rectangle(0, 0, 123, 0));
        setPreferredSize(new java.awt.Dimension(1450, 950));
        setVisible(false);
        getContentPane().setLayout(null);

        nom.setBackground(new java.awt.Color(0, 0, 0));
        nom.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        nom.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(nom);
        nom.setBounds(290, 260, 380, 39);

        pre.setBackground(new java.awt.Color(0, 0, 0));
        pre.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        pre.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pre);
        pre.setBounds(790, 250, 380, 39);

        tel.setBackground(new java.awt.Color(0, 0, 0));
        tel.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        tel.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(tel);
        tel.setBounds(790, 320, 218, 39);

        f.setBackground(new java.awt.Color(0, 0, 0));
        sexe.add(f);
        f.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        f.setForeground(new java.awt.Color(255, 255, 255));
        f.setText("Féminin");
        f.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fActionPerformed(evt);
            }
        });
        getContentPane().add(f);
        f.setBounds(290, 390, 115, 41);

        m.setBackground(new java.awt.Color(0, 0, 0));
        sexe.add(m);
        m.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        m.setForeground(new java.awt.Color(255, 255, 255));
        m.setText("Masculin");
        getContentPane().add(m);
        m.setBounds(430, 390, 125, 41);

        dd.setBackground(new java.awt.Color(0, 0, 0));
        dd.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        dd.setForeground(new java.awt.Color(255, 255, 255));
        dd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jour", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dd.setToolTipText("");
        dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddActionPerformed(evt);
            }
        });
        getContentPane().add(dd);
        dd.setBounds(290, 320, 90, 39);

        mm.setBackground(new java.awt.Color(0, 0, 0));
        mm.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        mm.setForeground(new java.awt.Color(255, 255, 255));
        mm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mois", "Janvier", "Février", "Mars", "Avril", "Mai", "Juin", "Juillet", "Août", "Septembre", "Octobre", "Novembre", "Décembre" }));
        getContentPane().add(mm);
        mm.setBounds(390, 320, 161, 39);

        yy.setBackground(new java.awt.Color(0, 0, 0));
        yy.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        yy.setForeground(new java.awt.Color(255, 255, 255));
        yy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Année", "2020", "2019", "2018", "2017", "2016", "2015", "2014", "2013", "2012", "2011", "2010", "2009", "2008", "2007", "2006", "2005", "2004", "2003", "2002", "2001", "2000", "1999", "1998", "1997", "1996", "1995", "1994", "1993", "1992", "1991", "1990", "1989", "1988", "1987", "1986", "1985", "1984", "1983", "1982", "1981", "1980", "1979", "1978", "1977", "1976", "1975", "1974", "1973", "1972", "1971", "1970", "1969", "1968", "1967", "1966", "1965", "1964", "1963", "1962", "1961", "1960", "1959", "1958", "1957", "1956", "1955", "1954", "1953", "1952", "1951", "1950", "1949", "1948", "1947", "1946", "1945", "1944", "1943", "1942", "1941", "1940", "1939", "1938", "1937", "1936", "1935", "1934", "1933", "1932", "1931", "1930", "1929", "1928", "1927", "1926", "1925", "1924", "1923", "1922", "1921", "1920", "1919", "1918", "1917", "1916", "1915", "1914", "1913", "1912", "1911", "1910", "1909", "1908", "1907", "1906", "1905", "1904", "1903", "1902", "1901", "1900" }));
        getContentPane().add(yy);
        yy.setBounds(560, 320, 114, 39);

        valider.setBackground(new java.awt.Color(0, 204, 51));
        valider.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        valider.setText("Valider");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });
        getContentPane().add(valider);
        valider.setBounds(500, 110, 350, 41);

        jLabel1.setFont(new java.awt.Font("Showcard Gothic", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Création d'un nouveau dossier médical");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(320, 20, 817, 45);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Nom:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 260, 64, 44);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 204, 0));
        jLabel3.setText("Prénom:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(680, 250, 110, 44);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 0));
        jLabel4.setText("Date de naissance:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 320, 222, 44);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 204, 0));
        jLabel5.setText("Sexe:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 390, 59, 44);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 204, 0));
        jLabel6.setText("Tel:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(740, 320, 42, 44);

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jButton1.setText("Annuler");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 110, 170, 41);

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jButton2.setText("Quitter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(940, 110, 170, 41);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taf/bg.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1450, 950);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  //dans le cas où l'utilisateur veut quitter le programme
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //un bouton annuler pour initialiser les champs au vide
        nom.setText("");
        pre.setText("");
        dd.setSelectedIndex(0);
        mm.setSelectedIndex(0);
        yy.setSelectedIndex(0);
        sexe.clearSelection();
        tel.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
//retrait des valeurs mis aux champs de la formulaire
String famname=nom.getText();
String name=pre.getText();
String day=dd.getSelectedItem().toString();
String month=mm.getSelectedItem().toString();
String year=yy.getSelectedItem().toString();
boolean sf=f.isSelected();
boolean sm=m.isSelected();
String phone=tel.getText();
int d=dd.getSelectedIndex();
int mo=mm.getSelectedIndex();
int y=yy.getSelectedIndex();
String s ="";
//selon quel boutton est séléctionné s aura la valeur du sexe
if(sf) s="Féminin";
else if(sm) s="Masculin";
             boolean v = false;//la valeur sera vrai si le dossier existe déjà
            /*verifier que le nom  est en lettres et espaces seulement*/
            boolean fn=true,fnn=true;
            for (int i=0;i<famname.length();i++){
            if ((!Character.isLetter(famname.charAt(i)))&&(!Character.isSpace(famname.charAt(i))))
            {fn=false; break;}}
            /*verifier que le prénom  est en lettres et espaces seulement*/
            for (int i=0;i<name.length();i++){
            if ((!Character.isLetter(name.charAt(i)))&&(!Character.isSpace(name.charAt(i))))
            {fnn=false; break;}}
             /*verifier la validité de la date sinon les index seront mis à 0*/
             boolean okay=true;
            switch(month){case "Février": if((day.equals("30"))||(day.equals("31")))
            {dd.setSelectedIndex(0);mm.setSelectedIndex(0);okay=false;} break;
            case "Avril": case"Juin": case"Septembre": case"Novembre": if(day.equals("31"))
            {dd.setSelectedIndex(0); mm.setSelectedIndex(0); okay=false;} break;}
            /*verifier que le numéro de téléphone est en chiffres seulement*/
            boolean t=true;
            for(int i=0;i<phone.length();i++)
            {if(!Character.isDigit(phone.charAt(i))) {t=false; break;}}   
            
//si les champs sont vides ou ne respectent pas les conditions
    if(famname.equals("")) JOptionPane.showMessageDialog(null,"Ecrire un nom SVP");
    else if(!fn)JOptionPane.showMessageDialog(null,"Nom invalide");  
    else if(name.equals("")) JOptionPane.showMessageDialog(null,"Ecrire un prénom SVP");
    else if(!fnn)JOptionPane.showMessageDialog(null,"Prénom invalide");    
     
    else if(day.equals("Jour")) JOptionPane.showMessageDialog(null,"Choisir un jour SVP");
    else if(month.equals("Mois")) JOptionPane.showMessageDialog(null,"Choisir un mois SVP");
    else if(okay==false){JOptionPane.showMessageDialog(null,"Date invalide");}
    else if(year.equals("Année")) JOptionPane.showMessageDialog(null,"Choisir une année SVP");   
            
    else if(!sf && !sm)JOptionPane.showMessageDialog(null,"Choisir un sexe  SVP");
            
    else if(phone.equals("")) JOptionPane.showMessageDialog(null,"Ecrire un numéro de téléphone SVP");
    else if((phone.length()!=8)||(t==false)) JOptionPane.showMessageDialog(null,"Numéro de téléphone invalide");
   //sinon si tout est bien
       else{
        try{Class.forName("com.mysql.jdbc.Driver");//création de la connexion avec la base
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");
        Statement st=conn.createStatement();
        String verif="SELECT * FROM dossier where Nom='"+famname+"' and Prenom='"+name+"' and Sexe='"+s+
       "' and tel='"+phone+"'";
        ResultSet rs=st.executeQuery(verif);
        if(rs.next())//si le dossier existe déjà alors v=true
        {v=true;}
       //s'il n'existe pas alors on l'insère avec la référence comme null puisqu'elle est mis à Auto Incrémentation dans la base
       //le premier sera 1 puis 2 etc. automatiquement 
        if(v==false){String sql="insert into dossier values(null,?,?,?,?,?,?,?)";
        //on Set les valeurs de la formulaire dans les champs dans une ligne de la base 
        PreparedStatement pstmt=conn.prepareStatement(sql);
        pstmt.setString(1,nom.getText());
        pstmt.setString(2,pre.getText());
        pstmt.setString(3,s);
        pstmt.setString(4,dd.getSelectedItem().toString());
        pstmt.setString(5,mm.getSelectedItem().toString());
        pstmt.setString(6,yy.getSelectedItem().toString());
        pstmt.setString(7,tel.getText());
        pstmt.executeUpdate();//insertion 
        JOptionPane.showMessageDialog(null,"Insertion aves succès");//message d'insertion
        //on re-met les champs à zéro
        nom.setText("");
        pre.setText("");
        dd.setSelectedIndex(0);
        mm.setSelectedIndex(0);
        yy.setSelectedIndex(0);
        sexe.clearSelection();
        tel.setText("");}
        //si v=false ( dossier existe déja)
        else {JOptionPane.showMessageDialog(null,"Patient existe déja");}
        //fermer la connection
        conn.close();
        }catch(Exception e)//s'il y a une exception elle sera affichée
        {JOptionPane.showMessageDialog(null,e);}}
          
    }//GEN-LAST:event_validerActionPerformed

    private void ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> dd;
    private javax.swing.JRadioButton f;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton m;
    private javax.swing.JComboBox<String> mm;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField pre;
    private javax.swing.ButtonGroup sexe;
    private javax.swing.JTextField tel;
    private javax.swing.JButton valider;
    private javax.swing.JComboBox<String> yy;
    // End of variables declaration//GEN-END:variables
}
